# Generated by Django 3.1.7 on 2021-04-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='progess',
            new_name='progress',
        ),
    ]
