# Generated by Django 3.2 on 2021-05-12 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20210512_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 22, 2, 12, 399576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='step',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
