# Generated by Django 3.2.4 on 2021-06-25 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20210512_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 4, 9, 13, 978255, tzinfo=utc)),
        ),
    ]
